spring:
  datasource:
    url: ${DB_DRIVER}://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: ${JPA_DIALECT}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}

fixer_io:
  baseUrl: ${FIXER_API_URL}
  access_key: ${FIXER_API_ACCESS_KEY}
  path_latest: ${FIXER_API_PATH_LATEST}
  scheduler:
    load-initial-delay: ${LOAD_RATES_INITIAL_DELAY_MS}
    load-fixed-delay: ${LOAD_RATES_FIXED_DELAY_MS}

rabbitmq:
  exchange:
    name: ${RABBITMQ_EXCHANGE}
  queue:
    name: ${RABBITMQ_QUEUE}
  routing:
    key: ${RABBITMQ_ROUTING}